export const BOARD_SIZE = 10;

export const DEFAULT_SHIPS = [
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'huge',
    length: 4,
    health: 4,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'large',
    length: 3,
    health: 3,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'large',
    length: 3,
    health: 3,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'medium',
    length: 2,
    health: 2,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'medium',
    length: 2,
    health: 2,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'medium',
    length: 2,
    health: 2,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'small',
    length: 1,
    health: 1,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'small',
    length: 1,
    health: 1,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'small',
    length: 1,
    health: 1,
    coordinates: [],
  },
  {
    position: { x: 0, y: 0 },
    direction: true,
    type: 'small',
    length: 1,
    health: 1,
    coordinates: [],
  },
];
